version: '3.6'

services:
    # Postgres db container
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER_FILE: /run/serets/pg_user`
            POSTRES_PASSWORD_FILE: /run/secrets/pg_password
            POSTGRES_DB_FILE: /run/secrets/pg_database
        secrets:
            - pg_password
            - pg_user
            - pg_database

    # Admin interface for postgres
    adminer:
        image: adminer
        ports:
            - 8080:8080
            


secrets:
    pg_user:
        external: true
    pg_password:
        external: true
    pg_database:
        external: true